name: supershop_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  carousel_slider: ^5.0.0
  dio: ^5.5.0+1
  provider: ^6.1.2
  intl: ^0.19.0
  input_quantity: ^2.4.0
  json_annotation: any
  flutter_widget_from_html: any
  device_info_plus: ^10.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  dart_jsonwebtoken: ^2.14.0
  sqflite: ^2.3.3+1
  collection: ^1.18.0
  easy_debounce: ^2.0.3
  flutter_slidable: ^3.1.1
  url_launcher: ^6.3.0
  qr_code_scanner: ^1.0.1
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  web_socket_channel: ^3.0.1
  material_design_icons_flutter: ^7.0.7296
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  mime: ^1.0.6
  app_links: ^6.3.2
  flutter_stripe: ^11.1.0

dev_dependencies:
  json_serializable: any
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Directory của hình ảnh
  assets:
    - assets/no-products.png
    - assets/no-orders.png
    - assets/facebookLogo.png
    - assets/googleLogo.png
    - assets/Qr_Scanner.png
    - assets/Shoppe_pay.png
    - assets/ShoppeCoin.png
    - assets/ShoppeLogo.png
    - assets/icon/icon.png
