name: Sync Folders to Main

on:
  push:
    branches: [app, api, web]

jobs:
  app-sync:
    if: github.ref == 'refs/heads/app'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
          fetch-depth: 0

      - name: Checkout app branch
        uses: actions/checkout@v4
        with:
          ref: app
          path: source

      - name: Clean other
        run: |
          cd source
          rm -rf api web .github 
          git add . && git commit -m "Clean branch" || echo "No cleanup needed"
          git push

      - name: Sync app folder
        run: |
          rsync -av --delete --exclude='.github' \
            "source/app/" \
            "main/app/"

      - name: Commit changes
        run: |
          cd main
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Auto-sync app from app branch"
            git push
          fi

  api-sync:
    if: github.ref == 'refs/heads/api'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
          fetch-depth: 0

      - name: Checkout api branch
        uses: actions/checkout@v4
        with:
          ref: api
          path: source

      - name: Clean other
        run: |
          cd source
          rm -rf app web .github 
          git add . && git commit -m "Clean branch" || echo "No cleanup needed"
          git push

      - name: Sync api folder
        run: |
          rsync -av --delete --exclude='.github' \
            "source/api/" \
            "main/api/"

      - name: Commit changes
        run: |
          cd main
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Auto-sync api from api branch"
            git push
          fi

  web-sync:
    if: github.ref == 'refs/heads/web'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
          fetch-depth: 0

      - name: Checkout web branch
        uses: actions/checkout@v4
        with:
          ref: web
          path: source

      - name: Clean other
        run: |
          cd source
          rm -rf api app .github 
          git add . && git commit -m "Clean branch" || echo "No cleanup needed"
          git push

      - name: Sync web folder
        run: |
          rsync -av --delete --exclude='.github' \
            "source/web/" \
            "main/web/"

      - name: Commit changes
        run: |
          cd main
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Auto-sync web from web branch"
            git push
          fi
