name: Sync Folders to Main

on:
  push:
    branches: [app, api, web]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          path: current

      - name: Clean other folders
        run: |
          cd current
          # Xóa thư mục không liên quan đến nhánh hiện tại
          if [[ "${GITHUB_REF##*/}" == "app" ]]; then
            rm -rf api web
          elif [[ "${GITHUB_REF##*/}" == "api" ]]; then
            rm -rf app web
          elif [[ "${GITHUB_REF##*/}" == "web" ]]; then
            rm -rf app api
          fi

          # Cấu hình thông tin commit
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Clean branch" || echo "No changes"
          git push

      - name: Sync current folder
        run: |
          TARGET_DIR="main/${GITHUB_REF##*/}"
          rsync -av --delete --exclude='.github' \
            "current/" \
            "$TARGET_DIR/"

      - name: Commit changes to main
        run: |
          cd main
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if ! git diff-index --quiet HEAD --; then
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git commit -m "Auto-sync ${GITHUB_REF##*/}"
            git push origin main
          fi

